config/routes.rb
Rails.application.routes.draw do
  resources :twitters
  root 'twitters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter.rb
class Twitter < ApplicationRecord
	validates :content, presence: true
    validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: [:show, :edit, :update, :destroy]
  def index
    @twitters = Twitter.all
  end
  def show
  end
  def new
    @twitter = Twitter.new
  end
  def edit
  end
  def create
    @twitter = Twitter.new(twitter_params)

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to @twitter, notice: 'Twitter was successfully created.' }
        format.json { render :show, status: :created, location: @twitter }
      else
        format.html { render :new }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @twitter.update(twitter_params)
        format.html { redirect_to @twitter, notice: 'Twitter was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter }
      else
        format.html { render :edit }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @twitter.destroy
    respond_to do |format|
      format.html { redirect_to twitters_url, notice: 'Twitter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_twitter
    @twitter = Twitter.find(params[:id])
  end

  def twitter_params
    params.require(:twitter).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header" style="height: 100px;">
        <nav class="navbar">
            <h1 style="color: white;">Twitter</h1>
            <ul class="nav-item" style="margin-left: 800px;">
            <li class="item"><%= link_to "Home", twitters_path %></li>
              <li class="item"><%= link_to " Tweet now", new_twitter_path %></li>
            </ul>
        </nav>
        <header>
    <%= yield %>
    <footer class="footer">
      <p class="foot-content"> <i> Copyright &copy; 2019  DUSENGUMUREMYIJean Doux</i></p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: twitter, local: true) do |form| %>
  <% if twitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twitter.errors.count, "error") %> prohibited this twitter from being saved:</h2>
      <ul>
      <% twitter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:"form-control", id:"exampleFormControlTextarea1"%>
  </div>
  <%= form.submit class:"btn btn-primary" %>
  <%= link_to 'Back', twitters_path, class:"btn" %>
</center>
<% end %>

app/views/twitters/edit.html.erb
<h1 style="text-align: center;">Editing Twitter</h1>

<%= render 'form', twitter: @twitter %>

app/views/twitters/index.html.erb
<p id="notice"><%= notice %></p>
<% @twitters.each do |twitter| %>
<center>
<div class="card" style="width: 500px;">
  <div class="card-header">
    Twitters
  </div>
  <div class="card-body">
    <p class="card-text"><%= twitter.content %></p>
    <%= link_to 'Show', twitter, class:"btn btn-success" %>
    <%= link_to 'Edit', edit_twitter_path(twitter), class:"btn btn-primary" %>
    <%= link_to 'Destroy', twitter, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
  </div>
</div>
<br>
<% end %>
<%= link_to 'New Twitter', new_twitter_path, class:"btn btn-warning" %>
</center>

app/views/twitters/new.html.erb
<h1 style="color: white;text-align: center;">New Twitter</h1>

<%= render 'form', twitter: @twitter %>

app/views/twitters/show.html.erb
<p id="notice"><%= notice %></p>
<center>
<p>
  <strong>Content:</strong><br>
  <%= @twitter.content %>
</p>
<%= link_to 'Comfirm', twitters_path, data: { confirm: 'Are you sure do you want to create a post' }, class:"btn btn-warning" %>
<%= link_to 'Back', edit_twitter_path(@twitter), class:"btn" %>
</center>